simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

tasks:
- type: "SingleInferenceTask"
  name: "h1_locomotion"
  env_num: 1
  offset_size: 1.0
  scene_asset_path: GRUtopia/assets/scenes/empty.usd
  robots:
  - name: h1
    prim_path: "/World/h1"
    type: "HumanoidRobot"
    position: [.0, .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
